// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319010230_AddPaymentScheduleDay")]
    partial class AddPaymentScheduleDay
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountReceived")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransportadoraId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TransportadoraId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PaymentSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TransportadoraId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Weekday")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TransportadoraId")
                        .IsUnique();

                    b.ToTable("PaymentSchedules");
                });

            modelBuilder.Entity("Pnr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataPnr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("RotaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RotaId");

                    b.ToTable("Pnrs");
                });

            modelBuilder.Entity("Rota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataRota")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadePacotes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransportadoraId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ValorFixo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorPorPacote")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotalCalculado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TransportadoraId");

                    b.ToTable("Rotas");
                });

            modelBuilder.Entity("Transportadora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transportadoras");
                });

            modelBuilder.Entity("Payment", b =>
                {
                    b.HasOne("Transportadora", "Transportadora")
                        .WithMany()
                        .HasForeignKey("TransportadoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transportadora");
                });

            modelBuilder.Entity("PaymentSchedule", b =>
                {
                    b.HasOne("Transportadora", "Transportadora")
                        .WithOne("PaymentSchedule")
                        .HasForeignKey("PaymentSchedule", "TransportadoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transportadora");
                });

            modelBuilder.Entity("Pnr", b =>
                {
                    b.HasOne("Rota", "Rota")
                        .WithMany("Pnrs")
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("Rota", b =>
                {
                    b.HasOne("Transportadora", "Transportadora")
                        .WithMany("Rotas")
                        .HasForeignKey("TransportadoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transportadora");
                });

            modelBuilder.Entity("Rota", b =>
                {
                    b.Navigation("Pnrs");
                });

            modelBuilder.Entity("Transportadora", b =>
                {
                    b.Navigation("PaymentSchedule");

                    b.Navigation("Rotas");
                });
#pragma warning restore 612, 618
        }
    }
}
